### ISSUE TITLE
电子科大那个加密真滴不知道咋搞

### ISSUE THREAD

**Issue by JRICKL** [ZimoLoveShuang/wisedu-unified-login-api#1]
太难了

**Comment by ZimoLoveShuang** [comment]
你是电子科技大学的吗？确实有点难搞，不过还是能搞，就是有点耗时间，慢慢磨

**Comment by JRICKL** [comment]
嗯嗯，前段时间想写个打卡脚本，就试试模拟登陆。发现加密比以前弄的要复杂，只有使用selenium这种方式搞了一个脚本

**Comment by ZimoLoveShuang** [comment]
优秀

**Comment by JRICKL** [comment]
大佬才厉害！

**Comment by ZimoLoveShuang** [comment]
我目前知道的情况是这样：你们电子科大的金智教务系统，先做了一次js混淆（这个还需要慢慢磨，但是目前我没有精力处理这个），然后提交登陆数据的时候密码经过了AES加密（这个都好弄，解决方案应该和我现在这个一样，代码实现在[AESHelper](https://github.com/ZimoLoveShuang/wisedu-unified-login-api/blob/master/src/main/java/wiki/zimo/wiseduunifiedloginapi/helper/AESHelper.java)里面）

**Comment by JRICKL** [comment]
好的，非常感谢！

**Comment by ZimoLoveShuang** [comment]
> 好的，非常感谢！

突然发现混淆没了，这样我的API项目就支持你们电子科大的模拟登录了

**Comment by JRICKL** [comment]
非常感谢你的提醒哈，我改天试试看呢
