### ISSUE TITLE
登录失败，URL无效

### ISSUE THREAD

**Issue by chinapsk** [ZimoLoveShuang/wisedu-unified-login-api#11]
api网页测试时，
Request URL
http://server:8080/wisedu-unified-login-api-v1.0/api/login?login_url=https%3A%2F%2Fcqmu.campusphere.net%2Fiap%2Flogin%3Fservice%3Dhttps%253A%252F%252Fcqmu.campusphere.net%252Fportal%252Flogin&password=PASSWORD&username=USERNAME
后，回报URL无效，报文为
{
  "msg": "login failed! Must supply a valid URL",
  "code": 1,
  "cookies": null
}

**Comment by ZimoLoveShuang** [comment]
Maybe you should provide your school, account, password and other information so that I can test and fix the bug. In order to protect privacy, it is recommended to send it privately. If you don't mind, you can scan the QR code and buy me a cup of milk tea.
