### ISSUE TITLE
云端启用WAF

### ISSUE THREAD

**Issue by Mysels** [ZimoLoveShuang/wisedu-unified-login-api#14]
目前Cas签到貌似全部失效
新版本Cookies 模式 : 
HWWAFSESID=2cf******; HWWAFSESTIME=1****

![图片](https://user-images.githubusercontent.com/26850454/110640382-bcd05680-81eb-11eb-9433-f496c4e656a8.png)

**Comment by LuckyTain** [comment]
相同问题

**Comment by Mysels** [comment]
直接撞盾了，rip

**Comment by Mysels** [comment]
目前已经解决
