### ISSUE TITLE
没有找到casLoginForm

### ISSUE THREAD

**Issue by CNYoki** [ZimoLoveShuang/wisedu-unified-login-api#17]
{
  "msg": "login failed! 网页中没有找到casLoginForm，请联系开发者！！！",
  "code": 1,
  "cookies": null
}

https://authserver.nwafu.edu.cn/authserver/login

**Comment by ZimoLoveShuang** [comment]
If you'd like to buy me a cup of milk tea, I'd be happy to help you fit it
