### ISSUE TITLE
今天用返回的的信息请求接口提示重新登陆

### ISSUE THREAD

**Issue by zerodayZHOUXUTIAN** [ZimoLoveShuang/wisedu-unified-login-api#7]
```
{
    "datas": {
        "WEC-REDIRECTURL": "/portal/login",
        "WEC-HASLOGIN": false
    },
    "code": 0,
    "message": "successs"
}
```
安徽师范大学的疫情签到接口
https://ahnu.campusphere.net/wec-counselor-collector-apps/stu/collector/queryCollectorProcessingList

**Comment by ZimoLoveShuang** [comment]
如果我没记错的话，你们学校是走的这个学校`安徽商贸职业技术学院`的认证

**Comment by zerodayZHOUXUTIAN** [comment]
所以 有参考吗？

**Comment by ZimoLoveShuang** [comment]
你把学校配置改成那个不就好了吗

**Comment by zerodayZHOUXUTIAN** [comment]
![image](https://user-images.githubusercontent.com/30335316/102481685-0140d000-409d-11eb-9ed2-e912fa16ac6c.png)

你好我好像没有看到安徽商贸职业技术学院的认证，请问可以说的详细点吗

**Comment by ZimoLoveShuang** [comment]
只需要把`auto-submit`项目里面的`config.yml`里面的`school`改了就可以了，可能会遇到一些小问题，比如今日校园更新了`api`，加群看看公告，或者你看看pr和issues，就能搞定，这个模拟登陆的项目有空你可以慢慢研究，希望你能从中学到一些东西吧，goot luck
