### ISSUE TITLE
[Potential Bug] Loop login  with wrong captcha may cause account to be locked

### ISSUE THREAD

**Issue by beetcb** [ZimoLoveShuang/wisedu-unified-login-api#8]
Using wrong `captcha`  to login too much  times  returns `HTTP 401 Unauthorized` every time , which will cause account to be locked(in my case in `whpu`). I think we can reduce `MAX_TRY_TIMES`  and prompt to api's user like: 
```js
验证码识别多次尝试失败，手动登录后可避免 API 的验证码识别过程
```

[source code reference](https://github.com/ZimoLoveShuang/wisedu-unified-login-api/blob/8847d03e1b243539f0c1af0bdc8e8579e66d0f2d/src/main/java/wiki/zimo/wiseduunifiedloginapi/process/WhpuCasLoginProcess.java#L123)

**Comment by ZimoLoveShuang** [comment]
关于验证码可以说明地方是：
1. 我没有针对性的训练`tesseract`，所以识别的准确率不算高，只有`60%-75%`，所以采取的临时策略是将`retry`的次数设置的比较大，其实我测试过，20次相对合理，既能够保证准确率又能够有效的保证接口的响应效率
2. 如果你保证**你提供的用户名和密码是正确的**，初试状态其实根本不会进入到验证码识别的流程，三次输错用户名和密码之后才会出现验证码，这点我在`application.yml`里面写过，防君子不防小人

优化的方向是：

1. 考虑自己训练一个模型来识别验证码以保证准确率在`90%`以上
2. 或者偷懒的做法，直接给提示，手动登陆一次便又恢复到开始时不需要验证码的状态

**Comment by beetcb** [comment]
嗯，主要是帮别人签到，有人会改了密码忘记告诉我：然后我的服务器默认重试一遍，就会造成这种问题了

**Comment by beetcb** [comment]
> 关于验证码可以说明地方是：
> 
> 1. 我没有针对性的训练`tesseract`，所以识别的准确率不算高，只有`60%-75%`，所以采取的临时策略是将`retry`的次数设置的比较大，其实我测试过，20次相对合理，既能够保证准确率又能够有效的保证接口的响应效率
> 2. 如果你保证**你提供的用户名和密码是正确的**，初试状态其实根本不会进入到验证码识别的流程，三次输错用户名和密码之后才会出现验证码，这点我在`application.yml`里面写过，防君子不防小人
> 
> 优化的方向是：
> 
> 1. 考虑自己训练一个模型来识别验证码以保证准确率在`90%`以上
> 2. 或者偷懒的做法，直接给提示，手动登陆一次便又恢复到开始时不需要验证码的状态

优化这边还可以在密码错误的时候不 throw exception , 而是作为 json 提示返回，这样在调用 api 时就可以加入相应异常处理了

**Comment by ZimoLoveShuang** [comment]
Maybe you should read `README.md` more carefully
![image](https://user-images.githubusercontent.com/32027313/102492835-32290100-40ad-11eb-9b37-280612192258.png)

**Comment by beetcb** [comment]
对不起，大意了。才看到 [`这里`](https://github.com/ZimoLoveShuang/wisedu-unified-login-api/blob/8847d03e1b243539f0c1af0bdc8e8579e66d0f2d/src/main/java/wiki/zimo/wiseduunifiedloginapi/controller/ApiController.java#L61) ，大佬考虑周到。偷懒提示用户确实可以考虑下，因为还有那些自己部署的用户，tesseract 训练包又会添加部署麻烦程度。
